services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: tallie-api-dev
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: development

      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

      REDIS_HOST: redis_cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    mem_limit: 1g
    cpus: '0.5'
    depends_on:
      - postgres_db
      - redis_cache
    volumes:
      - .:/usr/src/app
  #    command: pnpm run dev

  postgres_db:
    image: postgres:16-alpine
    container_name: tallie-db-dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    mem_limit: 512m
    cpus: '0.5'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_cache:
    image: redis:8-alpine
    container_name: tallie-redis-dev
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD} --maxmemory 256mb --maxmemory-policy allkeys-lru
    mem_limit: 512m
    cpus: '0.5'
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1s


volumes:
  postgres_data:
  redis_data:
